# This file specifies which linters golangci-lint should run.
#
# For descriptions of all available linters, run:
# target/bin/.golangci-lint-2.12.2 help linters
# or browse to:
# https://golangci-lint.run/docs/linters/

version: "2"
linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - goconst
  - goheader
  - gomodguard_v2
  - goprintffuncname
  - misspell
  - nakedret
  - nolintlint
  - predeclared
  - rowserrcheck
  - sqlclosecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace
  disable:
  - errcheck
  - staticcheck
  settings:
    depguard:
      rules:
        Main:
          allow:
          - $gostd
          - github.com/siggy/gographs
          - github.com/gorilla/mux
          - github.com/prometheus/client_golang
          - github.com/sirupsen/logrus
          - github.com/valkey-io/valkey-go
          - golang.org/x/tools/go/vcs
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
